export default [
  {
    title: "ANCILOSTOMÍASE OU AMARELÃO ",
    id: 11,
    image: "ANCILOSTOMÍASE",
    desciption: "Ancylostoma duodenale",
    desciption2: "Necator americanus",
  },
  {
    title: "ASCARIDÍASE",
    id: 22,
    image: "ASCARIDÍASE",
    desciption: "Ascaris lumbricoides",
    desciption2: "",
  },
  {
    title: "ENTEROBÍASE",
    id: 33,
    image: "ENTEROBÍASE",
    desciption: "Enterobius vermicularis",
    desciption2: "",
  },
  {
    title: "ESQUISTOSSOMOSE",
    id: 44,
    image: "ESQUISTOSSOMOSE",
    desciption: "Schistosoma mansoni",
    desciption2: "Biomphalaria",
  },
  {
    title: "FILARIOSE LINFÁTICA",
    id: 55,
    image: "FILARIOSE",
    desciption: "Wuchereria bancrofti",
    desciption2: "Culex",
  },
  {
    title: "TENÍASE",
    id: 66,
    image: "TENIASE",
    desciption: "Taenia solium",
    desciption2: "Taenia saginata",
  },
  {
    title: "TRICURÍASE",
    id: 77,
    image: "TRICURÍASE",
    desciption: "Trichiura trichiurus",
    desciption2: "",
  },
];
