export const allVermes = [
  {
    name: "ANCILOSTOMÍASE OU AMARELÃO ",
    answer: 3,
    id: 11,
    question:
      "Você Sabia que esta verminose é também conhecida como amarelão ou opilação pois causa uma intensa perda de sangue e a pessoa fica anêmica? ",
    content: [
      {
        title: "PARASITA",
        id: 11,
        text: "Esta infecção é causada pelos vermes _Ancylostoma _duodenale e _Necator _americanus.",
        image: "",
        text2: "",
        image2: "",
        subText: [
          {
            title: "Adultos",
            image2: "https://i.imgur.com/76zL0wK.jpg",
            text: "Os machos de _N. _Americanus medem de 5 a 9 mm de comprimento e na região posterior tem bolsa copuladora e dois espículos. As fêmeas medem 9 a 11 mm de comprimento e tem extremidade anterior afilada. Os machos de _A. _duodenale medem de 8 a 11 mm de comprimento, tem bolsa copuladora e dois espículos longos. As fêmeas tem de 10 a 18 mm de comprimento e cauda afilada. _N. _americanus tem lâminas cortantes na boca e A. duodenale tem dentes. ",
            image: "https://i.imgur.com/XIjDbdi.jpg",
          },
          {
            title: "Ovos",
            image2: "",
            text: "São liberados nas fezes do hospedeiro. somente visíveis ao microscópio ",
            image: "https://i.imgur.com/pxnNzwu.jpg",
          },
          {
            title: "Larvas",
            image2: "",
            text: "Do tipo rabidtóide. ",
            image: "https://i.imgur.com/F0IbqKW.jpg",
          },
          {
            title: "Hospedeiros",
            image2: "",
            text: "Somente o ser humano é hospedeiro deste parasita.",
            image: "",
          },
        ],
      },
      {
        title: "CICLO BIOLÓGICO",
        id: 11,
        text: "Os vermes adultos vivem no intestino delgado humano, seu hospedeiro definitivo. Os parasitas perfuram a mucosa intestinal e se alimentam de sangue. O ciclo de vida é do tipo monoxênico. Os adultos se reproduzem sexuadamente e liberam ovos.",
        image: "https://images2.imgbox.com/55/4f/nijdLeAK_o.jpg",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "CONTAMINAÇÃO",
        id: 11,
        text: "Ocorre pela penetração na pele de larvas do parasito no solo contaminado. ",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "SINTOMAS, DIAGNÓSTICO E TRATAMENTO",
        id: 11,
        text: "A penetração das larvas causa irritações na pele. A passagem da larva pelo sistema respiratório pode causar tosse, inflamação na garganta, febre, coriza, faringite, laringite, sensação de obstrução na garganta, dor ao falar e deglutir. A acentuada perda de sangue causada pelos vermes ancilostomídeos adultos provocam uma intensa anemia por deficiência de ferro, o que explica os sintomas como fraqueza, sonolência, indisposição, etc.",
        text2:
          "Os principais exames que atestam a presença dos parasitos são: clínico, laboratorial de sangue e parasitológico de fezes. O tratamento é realizado com drogas anti-helmínticas e reposição de ferro através de alimentação ou medicação.",
        image2: "",

        image: "",
        subText: [],
      },
      {
        title: "PROFILAXIA",
        id: 11,
        text: "Andar calçado, bons hábitos de higiene pessoal, saneamento básico e melhoria das condições socioeconômicas são as principais medidas preventivas da ancilostomíase. O tratamento medicamentoso preventivo também é importante, principalmente em escolares de zonas rurais.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
    ],
  },
  {
    name: "ASCARIDÍASE OU INFECÇÃO POR LOMBRIGA",
    id: 22,
    answer: 4,
    question:
      "Você sabia que esta doença é causada por um verme conhecido como lombriga ou “Bicha” e que nos casos mais sérios pode provocar obstrução intestinal?",
    content: [
      {
        title: "PARASITA",
        id: 22,
        text: "O causador desta infecção é o verme _Ascaris _lumbricoides.",
        image: "https://images2.imgbox.com/89/f7/ElJXrgJY_o.jpg",
        text2: "",
        image2: "",
        subText: [
          {
            title: "Adultos",
            image2: "",
            text: "Tem coloração amarelo-rosada e três lábios na extremidade anterior. O macho mede entre 15 e 30 cm de comprimento e tem a extremidade posterior afilada e encurvada. A fêmea mede de 35 a 40 cm de comprimento e com extremidade posterior retilínea.",
            image: "https://images2.imgbox.com/4a/e6/DqSdY1wx_o.jpg",
          },
          {
            title: "Ovos",
            image2: "",
            text: "Tem forma arredondada ou ovalada, com uma membrana de duplo contorno. São microscópicos e eliminados com as fezes. As fêmeas podem eliminar até 200 mil ovos por dia, os quais podem sobreviver meses ou até anos.",
            image: "https://images2.imgbox.com/59/b8/9BlmHYFt_o.jpg",
          },
          {
            title: "Larvas",
            image2: "",
            text: "Do tipo rabditoide que é liberada no intestino delgada após a chegada dos ovos. Essa larva atinge a corrente sanguínea e faz uma migração pelo organismo, passando pelo sistema respiratório e finalmente atingindo o intestino delgado.",
            image: "https://images2.imgbox.com/ba/19/Akz8iorW_o.jpg",
          },
          {
            title: "Hospedeiros",
            image2: "",
            text: "O único hospedeiro é o ser humano. ",
            image: "",
          },
        ],
      },
      {
        title: "CICLO BIOLÓGICO",
        id: 22,
        text: "Os vermes adultos vivem no intestino delgado, principalmente no jejuno e íleo. São dioicos e apresentam ciclo evolutivo do tipo monoxênico. ",
        text2: "",
        image2: "",
        image: "https://images2.imgbox.com/88/ae/AZenpIq1_o.jpg",
        subText: [],
      },
      {
        title: "CONTAMINAÇÃO",
        id: 22,
        text: "Através da ingestão de água ou alimentos contaminados com ovos do verme.",
        text2: "",
        image2: "",
        image: "",
        subText: [],
      },
      {
        title: "SINTOMAS, DIAGNÓSTICO E TRATAMENTO",
        id: 22,
        text: "Quando a carga parasitária é baixa em geral os sintomas são leves ou inexistentes. Com alta carga parasitária, porém podem ocorrer lesões hepáticas e pulmonares (provocadas pelas larvas); os vermes adultos podem provocar déficit nutricional, edema, urticária, convulsões, irritação na parede intestinal, obstrução intestinal (devido ao acúmulo de um grande número de vermes). Complicações ectópicas podem ocorrer no apêndice cecal, duto colédoco e os vermes podem sair pela boca e orelha, entrar na orelha média e na tuba auditiva.",
        text2:
          "Exame de fezes detectam os ovos da lombriga. O tratamento é feito com drogas anti-helmínticas.",
        image2: "",

        image: "",
        subText: [],
      },
      {
        title: "PROFILAXIA",
        id: 22,
        text: "Tratamento dos doentes, saneamento básico, educação para a saúde com noções de higiene pessoal e ambiental, tratamento da água, higienização e desinfestação de vegetais.",
        text2: "",
        image2: "",
        image: "",
        subText: [],
      },
    ],
  },
  {
    name: "ENTEROBÍASE",
    id: 33,
    answer: 4,
    question:
      "Você sabia que essa doença é muito conhecida por causa intensa coceira (prurido) no ânus e é bastante comum em crianças?",
    content: [
      {
        title: "PARASITA",
        id: 33,
        text: "Infecção intestinal causada pelo verme nematódeo da espécie _Enterobius _vermicularis. ",
        image: "",
        text2: "",
        image2: "",
        subText: [
          {
            title: "Adultos",
            image2: "",
            text: "Tem cor esbranquiçada, cutícula finamente estriada e boca pequena com três lábios retráteis. As fêmeas medem cerca de 1 cm de comprimento e tem extremidade posterior bastante afilada. Os machos medem 0,3 a 0,5 cm de comprimento e a cauda é bastante recurvada.",
            image: "https://images2.imgbox.com/38/a4/Wtq24kCY_o.jpg",
          },
          {
            title: "Ovos",
            image2: "",
            text: "Medem de 50 a 60 micrômetros de comprimento e tem um aspecto semelhante a letra “D”. Uma única fêmea grávida pode conter até 16 mil ovos.  A fêmea não coloca ovos no intestino para serem eliminados com as fezes. Ela migra grávida para a região anal onde provoca intenso prurido (coceira).",
            image: "https://images2.imgbox.com/68/d4/zpbnnSMV_o.jpg",
          },
          {
            title: "Larvas",
            image2: "",
            text: "Do tipo rabditoide que eclodem do ovo no duodeno. ",
            image: "https://images2.imgbox.com/3c/1a/3NlVG7TA_o.png",
          },
          {
            title: "Hospedeiros",
            image2: "",
            text: "Somente o ser humano é hospedeiro do parasita E. vermicularis.",
            image: "",
          },
        ],
      },
      {
        title: "CICLO BIOLÓGICO",
        id: 33,
        text: "Os vermes adultos vivem no apêndice cecal, livres ou aderidos e se alimentando de conteúdo intestinal do hospedeiro. As fêmeas carregadas de ovos são comumente encontradas no ânus e na região perianal. São dioicos e exibem ciclo do tipo monoxênico. ",
        image: "https://images2.imgbox.com/c8/57/j8ypWqt4_o.png",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "CONTAMINAÇÃO",
        id: 33,
        text: "É feita do ânus para a boca através das mãos. Pode ocorrer transmissão indireta por inalação de ovos em roupas, por exemplo.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "SINTOMAS, DIAGNÓSTICO E TRATAMENTO",
        id: 33,
        text: "A descida do parasita para a região próxima ao ânus causa intenso prurido anal, principalmente à noite e possivelmente irritações anais e perianais. O diagnóstico é feito com exame clínico, e detecção de ovos usando fita adesiva e posterior análise em microscópio no laboratório. O tratamento é feito com droga anti-helmíntica, ",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "PROFILAXIA",
        id: 33,
        text: "É focada no tratamento das pessoas contaminadas na família, hábitos de higiene pessoal, manejo adequado das roupas intimas e de cama usadas pelos indivíduos infectados. ",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
    ],
  },
  {
    name: "ESQUISTOSSOMOSE MANSONI",
    id: 44,
    answer: 1,
    question:
      "Você sabia que esta infecção parasitária causa um grande inchaço abdominal pelo acúmulo de líquido? A expressão “barriga d’água” é uma alusão a esta aparência causada pelo parasita. ",
    content: [
      {
        title: "PARASITA",
        id: 44,
        text: " É causada pelo verme platelminto parasita _Schistosoma _mansoni, que se aloja no sistema porta humano.",
        image: "",
        text2: "",
        image2: "",
        subText: [
          {
            title: "Adultos",
            image2: "",
            text: "O macho mede 1 cm e a fêmea 1,5 cm. A fêmea fica em um canal dentro do corpo do macho.  ",
            image: "https://images2.imgbox.com/b1/94/ExPqS6rw_o.png",
          },
          {
            title: "Ovos",
            image2: "",
            text: "São eliminados com as fezes. Tem cerca de 150 micrômetros de tamanho e apresentam um típico espinho. Somente são visíveis ao microscópio. ",
            image: "https://images2.imgbox.com/33/75/UmGV4I1H_o.jpg",
          },
          {
            title: "Larvas",
            image2: "https://images2.imgbox.com/42/6b/KmF4ffBE_o.png",
            text: "São de dois tipos: miracídios e cercarias. As larvas miracídios tem aproximadamente 180 micrômetros de comprimento e apresentam numerosos cílios que ajudam na locomoção na água. A larva cercaria tem aproximadamente 500 micrômetros de comprimento e uma típica cauda bifurcada. ",
            image: "https://images2.imgbox.com/80/ad/LI067YKC_o.png",
          },
          {
            title: "Hospedeiros",
            image2: "",
            text: "O ser humano é o hospedeiro definitivo e o caramujo do gênero _Biomphalaria é o hospedeiro intermediário.",
            image: "https://images2.imgbox.com/b4/2b/TQMZatL7_o.jpg",
          },
        ],
      },
      {
        title: "CICLO BIOLÓGICO",
        id: 44,
        text: "Os vermes adultos habitam o sistema porta humano. Após a cópula a fêmea libera ovos os quais são eliminados com as fezes. Quando os ovos atingem a água ocorre a liberação da larva cercária a qual procura caramujos do gênero _Biomphalaria onde penetram, se multiplicam e originam o segundo estágio larval conhecido como cercária. As cercarias são as formas infectantes a humanos.",
        image: "https://images2.imgbox.com/4d/da/uXHQYna6_o.jpg",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "CONTAMINAÇÃO",
        id: 44,
        text: "Através da penetração ativas de larvas cercarias na pele ao tomar banho em águas contaminadas. O caramujo é o vetor da doença. ",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "SINTOMAS, DIAGNÓSTICO E TRATAMENTO",
        id: 44,
        text: "Os Sintomas são: dermatite (inflamação na pele) devido a entrada das larvas, reação inflamatória do tipo granuloma em diversos órgãos, principalmente no fígado e inchaço do fígado e baço (hepatoesplenomegalia). A doença é detectada através de exame clínico e exame de fezes. A administração de medicamentos antiparasitários é utilizada para tratar a doença.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "PROFILAXIA",
        id: 44,
        text: "Controle dos caramujos transmissores, saneamento básico, instalações de água e esgoto sanitário evitar tomar banho em águas contaminadas, educação sanitária diagnóstico e tratamento dos casos humanos.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
    ],
  },
  {
    name: "FILARIOSE LINFÁTICA",
    id: 55,
    answer: 2,
    question:
      "Você sabia que a filariose linfática é também conhecida como elefantíase pois causa inchaço principalmente nas pernas? ",
    content: [
      {
        title: "PARASITA",
        id: 55,
        text: "A INFECÇÃO é causada pelo verme nematódeo parasita _Wuchereria _bancrofti, também conhecido como filaria, que afeta o sistema linfático humano. ",
        image: "https://images2.imgbox.com/e5/ce/qWaKywOh_o.jpg",
        subText: [
          {
            title: "Adultos",
            image2: "",
            text: "Tem corpo delgado e branco-leitoso. Os machos medem de 3,5 a 4 cm de comprimento com extremidade anterior afilada e a posterior enrolada. As fêmeas medem de 7 a 10 cm de comprimento.   ",
            image: "https://images2.imgbox.com/29/a4/wMtZAMR7_o.jpg",
          },
          {
            title: "Ovos",
            image2: "",
            text: "São vivíparos, ou seja, não colocam ovos. As fêmeas liberam no sistema cardiovascular as formas embrionárias chamadas microfilárias.",
            image: "",
          },
          {
            title: "Larvas",
            image2: "",
            text: "São encontradas no inseto vetor a partir do desenvolvimento das microfilárias.",
            image: "https://images2.imgbox.com/e0/0a/oFRx9XSr_o.jpg",
          },
          {
            title: "Hospedeiros",
            image2: "",
            text: "O hospedeiro intermediário é o mosquito do gênero _Culex e o hospedeiro definitivo é o ser humano.",
            image: "https://images2.imgbox.com/41/fb/mw5sFhfD_o.jpg",
          },
        ],
        text2: "",
        image2: "",
      },
      {
        title: "CICLO BIOLÓGICO",
        id: 55,
        text: "Os vermes adultos vivem no sistema linfático e sanguíneo humano. Podem viver por anos no organismo hospedeiro. São dioicos, com ciclo evolutivo do tipo heteroxênico. ",
        image: "https://images2.imgbox.com/df/ad/8DDtk5Fm_o.jpg",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "CONTAMINAÇÃO",
        id: 55,
        text: "Picada da fêmea infectada do inseto vetor do gênero _Culex. Esses insetos tem hábitos noturnos, justamente o período em que as microfilárias estão circulando no sangue periférico.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "SINTOMAS, DIAGNÓSTICO E TRATAMENTO",
        id: 55,
        text: "Os sintomas mais comuns são: linfangite (inflamação dos vasos linfáticos), linfadenite (inflamação dos gânglios linfáticos), febre, mal-estar. As manifestações crônicas compreendem o linfedema (inchaço ou edema linfático), hidrocele e elefantíase, que é o inchaço principalmente das pernas. O inchaço típico desta doença também pode progredir para o saco escrotal e mamas. ",
        text2:
          "O diagnóstico é clínico e com exame de sangue, onde se pesquisa a presença das microfilárias. O tratamento é feito com drogas antiparasitárias",
        image2: "",

        image: "",
        subText: [],
      },
      {
        title: "PROFILAXIA",
        id: 55,
        text: "Controle do vetor e uso de proteção contra a picada do mosquito.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
    ],
  },
  {
    name: "TENÍASE",
    id: 66,
    answer: 5,
    question:
      "Você sabia que as tênias ou solitárias podem atingir vários metros de comprimento vivendo dentro do intestino humano? ",
    content: [
      {
        title: "PARASITA",
        id: 66,
        text: "Infecção causada pelos parasitas _Taenia _solium e _Taenia _saginata também conhecidas popularmente como “solitárias”.",
        image: "",
        subText: [
          {
            title: "Adultos",
            image2: "https://images2.imgbox.com/8c/52/df3LHUke_o.jpg",
            text: "Os vermes adultos podem atingir de 3 a 10 metros de comprimento. Tem o corpo achatado e dividido em cabeça (ou escólex), pescoço e estróbilos (chamados proglotes). Em geral esses vermes são encontrados sozinhos no intestino, daí o nome solitárias. O escólex é armado com acúleos e ventosas. Não possuem boca e se alimentam absorvendo nutrientes do hospedeiro.",
            image: "https://images2.imgbox.com/7f/d1/k4Jc6rzF_o.jpg",
          },
          {
            title: "Ovos",
            image2: "",
            text: "São eliminados com a fezes junto com segmentos do corpo do verme (proglotes grávidas).",
            image: "https://images2.imgbox.com/42/0c/bfeoxB7l_o.jpg",
          },
          {
            title: "Larvas",
            image2: "https://images2.imgbox.com/ac/0e/76EGRSDI_o.jpg",
            text: "São chamadas de cisticerco, que se desenvolvem na musculatura ou sistema nervoso do hospedeiro intermediário. As larvas podem ser vistas a olho nu na carne e são conhecidas popularmente como “canjiquinhas”.",
            image: "https://images2.imgbox.com/41/79/dztFnPbf_o.png",
          },
          {
            title: "Hospedeiros",
            image2: "",
            text: "O hospedeiro intermediário da _Taenia _solium é o porco e da _Taenia _saginata é o boi. O ser humano é o hospedeiro definitivo do parasita. Caso o ser humano faça ingestão direta de proglotes do parasita ele desenvolverá a doença cisticercose humana, a qual pode ter sérias complicações.",
            image: "",
          },
        ],
        text2: "",
        image2: "",
      },
      {
        title: "CICLO BIOLÓGICO",
        id: 66,
        text: "É do tipo heteroxênico. Os adultos vivem no duodeno (intestino delgado) e são hermafroditas. Cada proglote contém estruturas reprodutoras de ambos os sexos e assim conseguem se autofecundar, gerando muitos ovos.",
        image: "https://images2.imgbox.com/e7/e8/PeDtqBD3_o.jpg",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "CONTAMINAÇÃO",
        id: 66,
        text: "Por meio de Ingestão de carne crua ou mal cozida contaminada com larvas cisticercos. ",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "SINTOMAS, DIAGNÓSTICO E TRATAMENTO",
        id: 66,
        text: "Os sintomas incluem bulimia, anorexia, náuseas, vômitos, dores abdominais, diarreias, constipação, fadiga, irritação, insônia, cefaléias (dores de cabeça) e vertigens. O diagnóstico pode ser feito por meio de exame de fezes. Drogas antiparasitárias são usadas pra eliminar o verme. ",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "PROFILAXIA",
        id: 66,
        text: "Fiscalização em matadouros e frigoríferos, cozinhar bem a carne, educação sanitária, tratamento dos doentes e saneamento básico.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
    ],
  },
  {
    name: "TRICURÍASE OU INFECÇÃO POR VERME-CHICOTE",
    id: 77,
    answer: 4,
    question:
      "Você sabia que 15% da população mundial esteve acometido por essa doença, principalmente em regiões tropicais e subtropicais.",
    content: [
      {
        title: "PARASITA",
        id: 77,
        text: "Infecção intestinal causada pelo verme _Trichiurus _trichiura, também conhecido por verme-chicote.",
        image: "",
        text2: "",
        image2: "",
        subText: [
          {
            title: "Adultos",
            image2: "",
            text: "Tem forma típica semelhante a um chicote. Os machos medem de 3 a 4,5 cm de comprimento e tem um espiculo na região terminal do corpo. As fêmeas medem de 4 a 5 cm. ",
            image: "https://images2.imgbox.com/40/bd/NMUxUwwg_o.jpg",
          },
          {
            title: "Ovos",
            image2: "",
            text: "Medem de 50 a 54 micrômetros e tem uma forma típica de barril com poros salientes e transparentes nas duas extremidades.",
            image: "https://images2.imgbox.com/6e/36/panoOaEb_o.png",
          },
          {
            title: "Larvas",
            image2: "",
            text: "Os ovos infectantes possuem uma larva de primeiro estágio. ",
            image: "",
          },
          {
            title: "Hospedeiros",
            image2: "",
            text: "O ser humano é o único hospedeiro do verme-chicote. ",
            image: "",
          },
        ],
      },
      {
        title: "CICLO BIOLÓGICO",
        id: 77,
        text: "É do tipo monoxênico. São dioicos e com nítido dimorfismo sexual. Parasitam o intestino grosso humano, principalmente o ceco e o cólon ascendente. A fêmea libera de 3 a 5 mil ovos por dia. ",
        image: "https://images2.imgbox.com/c5/6c/6m8YRiX2_o.jpg",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "CONTAMINAÇÃO",
        id: 77,
        text: "Por ingestão de ovos do parasito em águas e alimentos contaminados. ",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "SINTOMAS, DIAGNÓSTICO E TRATAMENTO",
        id: 77,
        text: "A maioria dos pacientes com carga parasitária leve são assintomáticos. Com a carga parasitária moderada ou alta podem surgir: dor de cabeça, dor epigástrica ou abdominal, diarreia (com ou sem sangue), náusea, vômito, anemia, desnutrição grave e em alguns casos lesões na mucosa intestinal e prolapso retal (intestino “pula” pra fora). O diagnóstico é clínico e laboratorial através de exame de fezes. Tratamento é realizado com drogas anti-helmínticas.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
      {
        title: "PROFILAXIA",
        id: 77,
        text: "Saneamento básico, higiene pessoal adequada e cuidados com os alimentos.",
        image: "",
        text2: "",
        image2: "",
        subText: [],
      },
    ],
  },
];
